### ISSUE TITLE
Featured request: keepalive another workflow that's not a part of keepalive workflow

### ISSUE THREAD

**Issue by sekedus** [liskin/gh-workflow-keepalive#3]
Please add a feature to keepalive another workflow that's not a part of keepalive workflow.

As implemented by: https://github.com/marketplace/actions/keepalive-workflow#advanced-use-cases

gh_mirror: https://gitea.com/sekedus/keepalive-workflow

**Comment by liskin** [comment]
> Please add a feature to keepalive another workflow that's not a part of keepalive workflow.
> 
> As implemented by: https://github.com/marketplace/actions/keepalive-workflow#advanced-use-cases

What's the motivation for this? You can:

1. use gh-workflow-keepalive in that another workflow (unless I'm missing a reason not to)
2. use https://github.com/marketplace/actions/keepalive-workflow instead

I mean, it certainly can be implemented in this one, but I'd love to understand why that's preferred to those 2 options.

**Comment by sekedus** [comment]
> 1. What's the motivation for this?

Keep multiple workflows active without needing to modify them individually.

<details>
<summary>Advanced use cases</summary>
<br>
Keeping another workflow file active using keepalive workflow with <code class="notranslate">workflow_files</code>.  

ㅤ
Lets assume that you have some build workflows:

- `.github/workflows/build1.yml`
```yaml
name: Build 20

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
```
- `.github/workflows/build2.yml`
```yaml
name: Build 19

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
```

You can keep both of these workflows active using the following keepalive workflow code:
```yaml
name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "build1.yml, build2.yml"
          time_elapsed: "0"
```
</details>

---
ㅤ
> 2. use https://github.com/marketplace/actions/keepalive-workflow instead

[![keepalive-workflow](https://github.com/user-attachments/assets/c8c7ccb8-1555-477c-b644-10bace050a4c)](https://github.com/gautamkrishnar/keepalive-workflow)
